SUCCESS in  benchmark_LORE.py  AND DSNAME  10
PROCESS TOOK 104 SECONDS ERROR in  benchmark_LORE.py  AND DSNAME  10 FOR C 0 AND ROW 0
