PROCESS TOOK 2400 SECONDS ERROR in  benchmark_LORE.py  AND DSNAME  11 FOR C 1 AND ROW 0
PROCESS TOOK 2400 SECONDS ERROR in  benchmark_LORE.py  AND DSNAME  11 FOR C 1 AND ROW 1
